name: Derekbrady
favicon: null
layout_spectrum: 0.048456194810569286
typography_spectrum: 0.4672479161527008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8786930942442268
  lightness: 0.48064374760724604
  saturation: 0.9175306290853769
  rhythmicContrast: 0.0910910670645535
purpose: []
