name: Derekbrady
favicon: null
layout_spectrum: 0.61683
typography_spectrum: 0.4672479161527008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#004fb6'
    - '#ffd900'
    - '#b2b2b2'
    - '#2fa8df'
  brandStrength: 0.5625
  lightness: 0.48064374760724604
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
